#@TYPE: Machine
#@NAME: Qualcomm Glymur Compute Reference Device
#@DESCRIPTION: Machine configuration for Qualcomm Glymur Compute Reference Device

require conf/machine/include/qcom-glymur.inc

MACHINE_FEATURES = "efi pci"

QCOM_DTB_DEFAULT ?= "glymur-crd"

KERNEL_DEVICETREE ?= " \
    qcom/glymur-crd.dtb \
"

# These DTs are not upstreamed and currently exist only in linux-qcom kernels
LINUX_QCOM_KERNEL_DEVICETREE ?= " \
    qcom/glymur-staging.dtbo \
"

# These DTs are not upstreamed and currently exist only in linux-qcom-next kernel
KERNEL_DEVICETREE:append:pn-linux-qcom-next = " \
    qcom/glymur-crd-camx.dtbo \
"

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += " \
    packagegroup-glymur-crd-firmware \
    packagegroup-glymur-crd-hexagon-dsp-binaries \
"

QCOM_CDT_FILE = "cdt_glymur_crd_0.1.0"
QCOM_BOOT_FILES_SUBDIR = "glymur-crd"
QCOM_PARTITION_FILES_SUBDIR ?= "partitions/glymur-crd/nvme"
QCOM_PARTITION_FILES_SUBDIR_SPINOR ?= "partitions/glymur-crd/spinor"

QCOM_BOOT_FIRMWARE = "firmware-qcom-boot-glymur"
QCOM_CDT_FIRMWARE = "firmware-qcom-cdt-glymur"
