#@TYPE: Machine
#@NAME: Qualcomm Kaanapali Development Kit
#@DESCRIPTION: Machine configuration for Qualcomm Kaanapali development Kit

require conf/machine/include/qcom-kaanapali.inc

MACHINE_FEATURES = "efi usbhost usbgadget alsa wifi bluetooth"

QCOM_DTB_DEFAULT ?= "kaanapali-mtp"

KERNEL_DEVICETREE ?= " \
                      qcom/kaanapali-mtp.dtb \
                      "

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += " \
    packagegroup-kaanapali-mtp-firmware \
    packagegroup-kaanapali-mtp-hexagon-dsp-binaries \
    qcom-fastcv-binaries-kaanapali-mtp-dsp \
"

QCOM_CDT_FILE = "cdt_kaanapali_mtp_0.4.0"
QCOM_BOOT_FILES_SUBDIR = "kaanapali"
QCOM_PARTITION_FILES_SUBDIR ?= "partitions/kaanapali-mtp/ufs"

QCOM_BOOT_FIRMWARE = "firmware-qcom-boot-kaanapali"
QCOM_CDT_FIRMWARE = "firmware-qcom-cdt-kaanapali"
