#@TYPE: Machine
#@NAME: Qualcomm RB3Gen2 Development Kit (Core Kit with open boot firmware)
#@DESCRIPTION: Machine configuration for Qualcomm RB3Gen2 development Kit, with QCS6490

require conf/machine/rb3gen2-core-kit.conf

EXTRA_IMAGEDEPENDS += "trusted-firmware-a-qcom"

MACHINE_FEATURES += "optee"
MACHINE_EXTRA_RRECOMMENDS += "${@bb.utils.contains('BBFILE_COLLECTIONS', 'meta-arm', 'packagegroup-optee', '', d)}"

PREFERRED_PROVIDER_virtual/bootloader = "u-boot-qcom"
