#@TYPE: Machine
#@NAME: Qualcomm RB3Gen2 Development Kit (Core Kit)
#@DESCRIPTION: Machine configuration for Qualcomm RB3Gen2 development Kit, with QCS6490

require conf/machine/include/qcom-qcs6490.inc

# NOTE: TPM hardware is only present on rb3gen2-industrial kit
MACHINE_FEATURES += "efi m2connector pci tpm2 phone"

KERNEL_DEVICETREE ?= " \
                      qcom/qcs6490-rb3gen2.dtb \
                      qcom/qcs6490-rb3gen2-industrial-mezzanine.dtbo \
                      qcom/qcs6490-rb3gen2-vision-mezzanine.dtbo \
                      "

# These DTs are not upstreamed and currently exist only in linux-qcom kernels
LINUX_QCOM_KERNEL_DEVICETREE ?= " \
                      qcom/qcs6490-rb3gen2-vision-mezzanine-camx.dtbo \
                      qcom/qcs6490-rb3gen2-staging.dtbo \
                      qcom/qcs6490-rb3gen2-industrial-mezzanine-staging.dtbo \
                      qcom/kodiak-el2.dtbo \
                      qcom/kodiak-staging.dtbo \
                      qcom/qcs5430-fps-camx.dtbo \
                      "

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += " \
    packagegroup-rb3gen2-firmware \
    packagegroup-rb3gen2-hexagon-dsp-binaries \
    packagegroup-rb3gen2-industrial-mezzanine-firmware \
    qairt-sdk-hexagon-v68 \
    qcom-fastcv-binaries-thundercomm-rb3gen2-dsp \
    qps615-dlkm \
"

QCOM_CDT_FILE = "cdt_core_kit"
QCOM_BOOT_FILES_SUBDIR = "qcm6490"
QCOM_PARTITION_FILES_SUBDIR ?= "partitions/qcs6490-rb3gen2/ufs"

QCOM_BOOT_FIRMWARE = "firmware-qcom-boot-qcs6490"
QCOM_CDT_FIRMWARE = "firmware-qcom-cdt-qcs6490"

# Isolate rt cpu
QCOM_RT_CPU        = "7"
QCOM_IRQAFF        = "0-6"
QCOM_RCU_NOCBS     = "7"
QCOM_RCU_EXPEDITED = "1"
QCOM_CPUIDLE_OFF   = "1"

UBOOT_CONFIG = "qcs6490-rb3gen2"
