#@TYPE: Machine
#@NAME: Qualcomm Shikra Alpha Evaluation Kit (EVK)
#@DESCRIPTION: Machine configuration for Qualcomm Shikra Evaluation Kit (EVK)

require conf/machine/include/qcom-shikra.inc

MACHINE_FEATURES += "efi pci phone"

KERNEL_DEVICETREE ?= " \
                      qcom/shikra-cqm-evk.dtb \
                      qcom/shikra-cqs-evk.dtb \
                      qcom/shikra-iqs-evk.dtb \
                      qcom/shikra-cqm-evk-imx577-camera.dtbo \
                      qcom/shikra-iqs-evk-imx577-camera.dtbo \
                      "

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += " \
    packagegroup-shikra-evk-firmware \
    packagegroup-shikra-evk-hexagon-dsp-binaries \
"

QCOM_CDT_FILE = "cdt_cq2390_itp_0.2.0"
QCOM_BOOT_FILES_SUBDIR = "shikra"
QCOM_PARTITION_FILES_SUBDIR ?= "partitions/shikra-evk/emmc"

QCOM_BOOT_FIRMWARE = "firmware-qcom-boot-shikra"
QCOM_CDT_FIRMWARE = "firmware-qcom-cdt-shikra"
