name: Build on PR
run-name: "${{ github.base_ref }}: ${{ github.event.pull_request.title }}"

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.github/.markdownlint.yaml'

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read
  actions: read

jobs:
  event-file:
    name: "Upload event file"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: Event File
        path: ${{ github.event_path }}
        
  pr-to-workflow-dependency:
    name: "PR To Workflow Dependency"
    uses: qualcomm/qcom-reusable-workflows/.github/workflows/qswat-reusable-pr-to-workflow-dependency.yml@qswat-release-v1
    with:
      workflow_id: ${{ github.run_id }}
      run_attempt: ${{ github.run_attempt }}
      pr_number: ${{ github.event.pull_request.number }}
      
  build-pr:
    uses: ./.github/workflows/build-yocto.yml
    with:
      profile: pr

